language: python
dist: trusty
notifications:
  email: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
cache: pip
compiler:
  - gcc
before_install:
  - SKLEARN_PORTER_HOME=$(pwd)
  - unset JAVA_TOOL_OPTIONS && unset _JAVA_OPTIONS
install:
  - npm install xmlhttprequest
  - pip install -U pip
  - make install.requirements.development
before_script:
  - gcc --version
  - java -version
  - node --version
  - go version
  - php --version
  - ruby --version
  - python --version
script:
  - make test
